name: ds
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.13.5
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - ipykernel
  - duckdb
  - plotly
  - pip
  - pip:
      - polars
