---
name: CI
'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ds-zero-to-one
        shell: bash -l {0}         # 👈 ensure conda activation is visible to steps
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          auto-activate-base: false
          conda-remove-defaults: true
          channels: conda-forge
          channel-priority: strict
          environment-file: ds-zero-to-one/environment.yml
          activate-environment: ds

      - name: Sanity check
        run: |
          conda info
          which python
          python -c "import pandas, duckdb, polars as pl; print('CI env OK')"
