---
name: CI
'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ds-zero-to-one
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: ds
          environment-file: ds-zero-to-one/environment.yml
          channels: conda-forge
          channel-priority: strict
          use-mamba: true
          conda-remove-defaults: true   # 👈 stop implicit 'defaults'

      - name: Sanity check
        run: python -c "import pandas, duckdb, polars as pl; print('CI env OK')"
