---
name: CI
'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ds-zero-to-one
    steps:
      - uses: actions/checkout@v4

      # Use Miniforge (conda-forge bootstrap) with mamba
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: true
          environment-file: ds-zero-to-one/environment.yml

      - name: Sanity check
        run: python -c "import pandas, duckdb, polars as pl; print('CI env OK')"
